fix(dashmate): incorrect reset command prompt in case network is already set up
dashevo/platform pull request #1064
Opened 2023-05-10 15:35 UTC by shuplenkov

## Issue being fixed or feature implemented

In case if the network is already set up and a user tries to set up again he sees incorrect command hint

## What was done?

Wrong error prompt was replaced with th correct one

## How Has This Been Tested?

Manual

## Breaking Changes

No

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2023-05-10 15:46 UTC, shumkov requested changes

2023-05-11 08:59 UTC, shumkov requested changes

2023-05-11 08:59 UTC, shumkov commented on packages/dashmate/src/commands/setup.js
> +              ? 'dashmate group reset --hard' : `dashmate reset --config ${ctx.preset} --hard`;
```suggestion
              ? 'dashmate group reset --group=local --hard' : `dashmate reset --config=${ctx.preset} --hard`;
```

2023-05-11 10:37 UTC, shuplenkov commented on packages/dashmate/src/commands/setup.js
> +              ? 'dashmate group reset --hard' : `dashmate reset --config ${ctx.preset} --hard`;
We don't have such option

2023-05-11 12:08 UTC, shumkov approved these changes
👍

2023-05-11 17:31 UTC, merged