build: autodetect and install correct wasm-bindgen-cli version
dashevo/platform pull request #1076
Opened 2023-05-12 07:56 UTC by lklimek

## Issue being fixed or feature implemented

wasm-bindgen-cli version must match wam-bindgen dependency version

## What was done?

* install cargo-lock in deps image
* autodetect wasm-bindgen-cli version in build-wasm.sh
* bump wasm-bindgen to 0.2.85

## How Has This Been Tested?

Local network, Github Actions

## Breaking Changes

Locally installed version of wasm-bindgen-cli will be overwritten.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-05-16 11:13 UTC, strophy submitted a review, later dismissed

2023-05-16 11:16 UTC, shumkov requested changes
Multiple tests are failed

2023-05-16 11:16 UTC, shumkov commented on .github/actions/docker/action.yaml
> +      - test-suite
These params are not supported for action input, they are only for workflow input which is different

2023-05-17 09:10 UTC, shumkov requested changes

2023-05-17 09:10 UTC, shumkov commented on Dockerfile
> +COPY Cargo.lock .
that will invalidate layer cache pretty often. maybe we just stick on specific version of this library?

2023-05-25 07:26 UTC, shumkov commented on Dockerfile
> +COPY Cargo.lock .
Agreed to revert changes in Dockerfile

2023-05-26 09:03 UTC, shumkov commented on Dockerfile
> +    cargo install --profile "${CARGO_BUILD_PROFILE}" wasm-bindgen-cli@0.2.85 && \
Do we actually need to use profile here?

2023-05-26 11:04 UTC, shumkov approved these changes
👍

2023-05-26 11:04 UTC, merged