feat(dpp)!: do not allow creating data contracts without documents
dashevo/platform pull request #1675
Opened 2024-01-18 18:02 UTC by markin-io

## Issue being fixed or feature implemented

`check_tx` now will throw an error in case data contract schema is empty

## What was done?

- Added new error type
- Added wasm binings

## How Has This Been Tested?

- Added new test to test-suite

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-01-18 18:43 UTC, shumkov requested changes

2024-01-18 18:43 UTC, shumkov commented on packages/platform-test-suite/test/functional/platform/DataContract.spec.js
> +    it('should fail to create new data contract with empty schema', async () => {
Do you think we need a test for this in test suite? Maybe just in DPP?

2024-01-18 18:43 UTC, shumkov commented on packages/rs-drive-abci/src/execution/validation/state_transition/state_transitions/data_contract_create/structure/v0/mod.rs
>          let result = DataContract::try_from_platform_versioned(
Actual schema validation is happening here for each document type https://github.com/dashpay/platform/blob/10954c2355903c42ff17a2c3f7f57a5f674621ce/packages/rs-dpp/src/data_contract/document_type/class_methods/try_from_schema/mod.rs#L11

We need to validate here that we document types are defined https://github.com/dashpay/platform/blob/10954c2355903c42ff17a2c3f7f57a5f674621ce/packages/rs-dpp/src/data_contract/document_type/class_methods/create_document_types_from_document_schemas/mod.rs#L35

2024-01-18 20:35 UTC, thephez commented
Technically this is a breaking change, right?

2024-02-12 08:53 UTC, shumkov requested changes

2024-02-12 08:53 UTC, shumkov commented on packages/platform-test-suite/test/functional/platform/DataContract.spec.js
> +    DataContractEmptySchemaError,
Never used

2024-02-16 16:03 UTC, shumkov approved these changes
👍

2024-02-16 16:04 UTC, merged