feat(sdk): add query for data contract history
dashevo/platform pull request #1787
Opened 2024-03-18 12:28 UTC by markin-io

## Issue being fixed or feature implemented

Added data contract history query to rs-sdk

## What was done?

- Added limit query
- Added test

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-04-16 09:02 UTC, lklimek commented
Checklist:

1. [X] Ensure protobuf messages are defined in `packages/dapi-grpc/protos/platform/v0/platform.proto` and generated
   correctly in `packages/dapi-grpc/src/platform/proto/org.dash.platform.dapi.v0.rs`.
2. [X] In `packages/dapi-grpc/build.rs`, add `Request` to `VERSIONED_REQUESTS` and response `Response` to `VERSIONED_RESPONSES`.
   This should add derive of `VersionedGrpcMessage` (and some more) in `org.dash.platform.dapi.v0.rs`.
3. [X] Link request and response type to dapi-client by adding appropriate invocation of `impl_transport_request_grpc!` macro
in `packages/rs-dapi-client/src/transport/grpc.rs`.
4. [ ] If needed, implement new type in `packages/rs-drive-proof-verifier/src/types.rs` to hide complexity of data structures
   used internally.

   If you intend to implement `FetchMany`, you should define type returned by `fetch_many()` using `RetrievedObjects`
   that will store collection of  returned objects, indexd by some key.
5. [X] Implement `FromProof` trait for the `Object` (or type defined in `types.rs`) in `packages/rs-drive-proof-verifier/src/proof.rs`.
6. [X] Implement `Query` trait for the `Request` in `packages/rs-sdk/src/platform/query.rs`.
7. [X] Implement `Fetch\<Request\>` trait for the `Object` (or type defined in `types.rs`) in `packages/rs-sdk/src/platform/fetch.rs`.
8. [ ] Implement `FetchMany\<Request\>` trait for the `Object` (or type defined in `types.rs`) in `packages/rs-sdk/src/platform/fetch_many.rs`.
9. [X] Add `mod ...;` clause to `packages/rs-sdk/tests/fetch/main.rs`
10. [X] Implement unit tests in `packages/rs-sdk/tests/fetch/*object*.rs`
11. [X] Add name of request type to match clause in `packages/rs-sdk/src/mock/sdk.rs` : `load_expectations()`
12. [ ] Start local devnet with `yarn reset ; yarn setup && yarn start`
13. [X] Generate test vectors with script `packages/rs-sdk/scripts/generate_test_vectors.sh`

2024-04-16 09:05 UTC, lklimek requested changes

2024-04-16 09:05 UTC, lklimek commented on packages/rs-sdk/tests/fetch/data_contract.rs
> +        "3c71ba2d0b655ac3d231c4411d3c3fad43451d3f48213537ff9da331b24e5dea",
Maybe use `Config::existing_data_contract_id`?

2024-04-25 06:45 UTC, lklimek approved these changes

2024-04-25 09:51 UTC, shumkov approved these changes

2024-04-25 10:23 UTC, merged