feat(dapi)!: split getStatus into two endpoints
dashevo/platform pull request #1812
Opened 2024-04-11 12:00 UTC by markin-io

## Issue being fixed or feature implemented

Reworked getStatus query to not do Masternode related RPC reuqests 

## What was done?

Removed unnecessary and performance heavy `getMnSync('status')` and `getMasternode('status')` Core RPC calls from `getStatus` handler

## How Has This Been Tested?

CI

## Breaking Changes

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2024-04-13 19:02 UTC, riongull commented
Hey @markin-io could you give some more context about what this is about?  It's a pretty big PR.  What's the motivation, what are the removals being replaced with, etc.  Thanks!

2024-04-22 00:39 UTC, shumkov requested changes
I was speaking with some people and community and it seems masternode status is something what people is using. Shall we just move it to a separate endpoint instead of removing? `getMasternodeStatus`? In this case it's probably make sense to rename `getStatus` to `getBlockchainStatus`

2024-04-23 08:27 UTC, shumkov requested changes

2024-04-23 08:27 UTC, shumkov commented on packages/dapi-grpc/clients/core/v0/nodejs/CorePromiseClient.js
> +            GetCoreChainStatusRequest: PBJSGetCoreChainStatusRequest,
We already in Core service. There is no need to point to Core again. I think we agreed on `getBlockchainStatus` (similar to Core RPC command name).

2024-04-23 12:23 UTC, shumkov requested changes

2024-04-23 12:23 UTC, shumkov commented on packages/dapi/lib/grpcServer/handlers/core/getBlockchainStatusHandlerFactory.js
> +    chain.setIsSynced(blockchainInfoResponse.verificationprogress === 1);
Isn't it's a float?

2024-04-23 12:42 UTC, shumkov commented on packages/dapi/lib/grpcServer/handlers/core/getBlockchainStatusHandlerFactory.js
> +    chain.setIsSynced(blockchainInfoResponse.verificationprogress === 1);
Oh, that's JS :))

2024-04-23 12:42 UTC, shumkov submitted a review, later dismissed
👍

2024-04-23 14:50 UTC, shumkov approved these changes

2024-04-24 08:14 UTC, merged