fix(package.json): update links to correct URLs for "homepage", "repository.url", "bugs.url"
dashevo/platform pull request #2068
Opened 2024-08-22 23:55 UTC by Validark

Updated the package.json files to reflect the move to the monorepo.
**Note:** I did not update the versions of the package.json files. I presume that would happen immediately before pushing to npm?

## Issue being fixed or feature implemented

Helps npm point to the right location

## What was done?

Updated links in the package.json files. In each package.json file:
  - "repository.url" was set to "git+https://github.com/dashpay/platform.git"
  - "bugs.url" was set to "https://github.com/dashpay/platform/issues"
  - "homepage" was set to the directory of the package

## How Has This Been Tested?

n/a

## Breaking Changes

none

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have added "!" to the title and described breaking changes in the corresponding section if my code contains any
- [ ] I have made corresponding changes to the documentation if needed

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2024-08-23 00:03 UTC, Validark commented
Are the homepages supposed to point to the `v1.1-dev` branch? Not really sure what to do about that.

2024-08-23 08:22 UTC, lklimek commented
> Are the homepages supposed to point to the `v1.1-dev` branch? Not really sure what to do about that.

Maybe HEAD, for example https://github.com/dashpay/platform/tree/HEAD/packages/dashpay-contract#readme ?

2024-08-24 04:45 UTC, shumkov requested changes

2024-08-24 04:45 UTC, shumkov commented on packages/dapi-grpc/package.json
> +  "homepage": "https://github.com/dashpay/platform/tree/v1.1-dev/packages/dapi-grpc#readme",
It's better to use master. `v1.1-dev` will be deleted at some point.

2026-03-30 14:53 UTC, thepastaclaw commented
<!-- thepastaclaw-gate v1 -->
### Review Gate

Commit: `02bd23ce`

- ✅ **Debounce**: 843460m ago (need 30m)
- ✅ **CI checks**: no CI checks found
- ⏳ **CodeRabbit review**: no comment yet

- [ ] Run review now (check to override)

2026-03-31 17:36 UTC, closed without merging