feat: create withdrawal keys for masternode identities
dashevo/platform pull request #320
Opened 2022-04-01 16:12 UTC by shuplenkov

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-04-06 14:07 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/createMasternodeIdentityFactory.js
> +        securityLevel: IdentityPublicKey.SECURITY_LEVELS.MASTER,
Should be different

2022-04-06 14:09 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/createMasternodeIdentityFactory.js
> +    withdrawPubKeyData,
payoutScript

2022-04-06 14:09 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/createMasternodeIdentityFactory.js
> +        readonly: false,
Camel case

2022-04-06 14:27 UTC, shumkov requested changes

2022-04-06 14:27 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/handleUpdatedScriptPayoutFactory.js
> +    );
Let's add maxId to Identitiy. It will be useful in SDK

2022-04-06 14:27 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/handleUpdatedScriptPayoutFactory.js
> +      : IdentityPublicKey.TYPES.ECDSA_HASH160;
We can extract this logic into a separate function

2022-04-06 14:27 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/handleUpdatedScriptPayoutFactory.js
> +    await transactionalStateRepository.storeIdentity(identity);
We need to make sure that we are not reaching the limit of public keys for identity. If we reached the limit just do not add a new key.

2022-04-06 14:27 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
> +          && previousMnListEntry.scriptPayout !== mnEntry.scriptPayout
We need to make sure we updated Core to 0.19-dev

2022-05-02 13:12 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/handleUpdatedScriptPayoutFactory.js
> +      if (Buffer.compare(pk.getData(), previousPubKeyData) === 0) {
```suggestion
      if (pk.getData().equals(previousPubKeyData)) {
```

2022-05-02 13:14 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
> +            new Script(previousPayoutAddress).toBuffer(),
Will it work if previous is undefined?

2022-05-02 14:00 UTC, shuplenkov commented on packages/js-drive/lib/identity/masternode/synchronizeMasternodeIdentitiesFactory.js
> +            new Script(previousPayoutAddress).toBuffer(),
yes. There is a test for that

2022-05-02 14:07 UTC, shumkov approved these changes
Good job! 👍

2022-05-04 12:48 UTC, shumkov approved these changes
Good job! 👍

2022-05-04 17:51 UTC, shumkov approved these changes

2022-05-04 17:52 UTC, merged