feat!: Identity master key can be used only to update identity
dashevo/platform pull request #384
Opened 2022-05-10 11:09 UTC by shuplenkov

## Issue being fixed or feature implemented

From security considerations, the master key should be used only for updating and disabling identity. For signing other state transitions we need to create another authorization key with security level - high. 

## What was done?

Changed state transition signature validation

## How Has This Been Tested?

With tests

## Breaking Changes

"High" security level keys must be used insted of "master"

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2022-05-11 05:02 UTC, shumkov requested changes

2022-05-11 05:02 UTC, shumkov commented on packages/js-dpp/lib/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.js
> +    if (
Shouldn't we use here `getKeySecurityLevelRequirement()` as well?

2022-05-11 10:05 UTC, shumkov commented on packages/dashmate/configs/schema/configJsonSchema.js
> +            highPublicKey: {
We need master keys to create system identities in Drive. Agreed to rename "high" with "second"

2022-05-12 06:55 UTC, shumkov requested changes

2022-05-12 06:55 UTC, shumkov commented on packages/js-dpp/lib/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.js
> +        );
This is impossible due to check above so we can skip this one.

2022-05-12 06:55 UTC, shumkov commented on packages/js-dpp/lib/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.js
> +        );
This is checking in basic validation so we can skip it

2022-05-12 06:55 UTC, shumkov commented on packages/js-dpp/lib/stateTransition/validation/validateStateTransitionIdentitySignatureFactory.js
> +        );
This is impossible due to check above

2022-05-12 12:12 UTC, shumkov commented on packages/js-dpp/lib/errors/consensus/signature/InvalidIdentityPublicKeyTypeError.js
>  class InvalidIdentityPublicKeyTypeError extends AbstractSignatureError {
Do we use it anywhere?

2022-05-12 12:14 UTC, shumkov commented on packages/js-dpp/lib/errors/consensus/signature/PublicKeyIsDisabledError.js
> +   * @param {IdentityPublicKey} publicKey
We can't pass objects like that into consensus error due to serialization. It must be types supported by cbor. I would recommend to pass key ID

2022-05-12 12:18 UTC, shumkov commented on packages/js-dpp/lib/stateTransition/AbstractStateTransitionIdentitySigned.js
> +    if (
Shouldn't it be vice-versa? I mean it should go from what state transition require but not from what key we are passing. Isn't?

2022-05-12 12:47 UTC, shumkov commented on packages/js-dpp/lib/stateTransition/AbstractStateTransitionIdentitySigned.js
> +    return IdentityPublicKey.SECURITY_LEVELS.HIGH;
We need to set master to IdentityUpdateTransition class

2022-05-12 13:07 UTC, shumkov requested changes
signatureSecurityLevelRequirement in DataContract shouldn't allow to set MASTER

2022-05-12 13:33 UTC, shumkov commented on packages/js-dpp/lib/errors/consensus/signature/MasterPublicKeySecurityLevelIsNotAllowedError.js
> +const AbstractSignatureError = require('./AbstractSignatureError');
Is not using anywhere

2022-05-12 13:43 UTC, shuplenkov commented on packages/js-dpp/lib/errors/consensus/signature/InvalidIdentityPublicKeyTypeError.js
>  class InvalidIdentityPublicKeyTypeError extends AbstractSignatureError {
Yes

2022-05-13 11:02 UTC, shumkov commented on packages/platform-test-suite/test/e2e/masternodeRewardShares.spec.js
> +      const account = await client.platform.client.getWalletAccount();
It's not a test so let's move to `before`

2022-05-13 15:56 UTC, shumkov approved these changes
Good job! 👍

2022-05-13 15:56 UTC, merged