feat(sdk): separate wallet persistence storage by walletId
dashevo/platform pull request #407
Opened 2022-05-24 07:59 UTC by pshenmic

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-05-30 07:20 UTC, markin-io requested changes
Good job! Let's do some minor tweaks and we're good to go

2022-05-30 07:20 UTC, markin-io commented on packages/wallet-lib/src/types/WalletStore/methods/exportState.js
> +    walletId,
I think we don't need it there. Wallet id is already known from the root object. And at importState as well

2022-05-30 07:20 UTC, markin-io commented on packages/wallet-lib/src/types/Storage/methods/rehydrateState.js
> +const rehydrateState = async function rehydrateState(walletId) {
Let's leave this function signature intact to not introduce unnecessary changes to the documentation.
You can access a wallet Id with `this.currentWalletId`

2022-05-30 12:36 UTC, markin-io submitted a review, later dismissed
utACK

2022-05-31 13:25 UTC, markin-io approved these changes

2022-05-31 13:49 UTC, merged

2022-06-01 16:14 UTC, thephez commented
This PR has a v0.22.x milestone, but was merged into 0.23-dev. Is there a plan to backport to 0.22 or is the milestone just incorrect?

2022-06-01 16:42 UTC, markin-io commented
@thephez thanks. Updated to a correct milestone. 
It will be backported to v0.22 as well

2022-06-02 04:19 UTC, shumkov commented
Won't it be a breaking change?

2022-06-02 06:27 UTC, markin-io commented
> Won't it be a breaking change?

No, it will wipe old storage and re-sync from the beginning.