feat: limit the number of shares for masternode by 1
dashevo/platform pull request #432
Opened 2022-06-10 13:14 UTC by shuplenkov

## Issue being fixed or feature implemented

## What was done?

## How Has This Been Tested?

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-06-13 08:12 UTC, shumkov requested changes

2022-06-13 08:12 UTC, shumkov commented on packages/js-drive/lib/identity/masternode/createRewardShareDocumentFactory.js
> +    const fetchedDocumentsResult = await documentRepository.find(
I would keep only one query and check both number of docs and `payToId` equals to an operator in one of them.

2022-06-13 09:04 UTC, shumkov approved these changes
👍

2022-06-13 10:35 UTC, merged

2022-06-20 17:37 UTC, thephez commented
@PastaPastaPasta @QuantumExplorer If [DIP-26](https://github.com/dashpay/dips/blob/master/dip-0026.md#registering-a-masternode-proregtx-and-updating-registrar-of-masternode-proupregtx) is implemented in Core, it should be updated to align with this, correct? It wouldn't make sense to have a mismatch between Core/Platform MN shares.