fix(dashmate): remove DOCKER_COMPOSE_V2 check
dashevo/platform pull request #433
Opened 2022-06-13 08:58 UTC by pshenmic

## Issue being fixed or feature implemented

Remove checks for legacy docker-compose commands, as we only support docker compose v2 now.

## What was done?

Removed the check for DOCKER_COMPOSE_V2 flag and `docker-compose` command presence.

## How Has This Been Tested?

Locally

## Breaking Changes

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2022-06-13 09:09 UTC, strophy commented
Let's specify `DockerCompose.DOCKER_COMPOSE_MIN_VERSION = '2.0.0'` on line 418?

2022-06-13 09:24 UTC, shumkov requested changes
There is one more in DockerCompose#up

2022-06-14 15:52 UTC, shumkov commented on packages/dashmate/src/docker/DockerCompose.js
> +      await dockerCompose.upAll({
We probably need to pass `no-build` flag there?

2022-06-21 06:59 UTC, pshenmic commented
Closing in favor of https://github.com/dashevo/platform/pull/441

2022-06-21 06:59 UTC, closed without merging