feat(dashmate): upgrade docker compose to v2
dashevo/platform pull request #441
Opened 2022-06-20 06:25 UTC by pshenmic

## Issue being fixed or feature implemented

Docker has introduced new Docker Compose v2 engine few years ago, which is now bundled with Docker and does not require installing additional packages. There is a completely new and rewritten core engine in Go that also features a lot of new cool things. Along with that, older v1 docker-compose binaries will soon become deprecated. The syntax of the commands switched to `docker compose` instead of `docker-compose`, and legacy commands.

Previously, you had to enable this feature to use v2. But now it is enabled out of the box on every system, and since its inconvenient to tell users to install outdated tools and we already require Docker v20.10+, we can safely migrate to new commands.

This upgrade will keep our project up to date with latest Docker features and also will remove the require of installing additional tools like docker-compose.

## What was done?

* Forked docker-compose package to our github and made changes to make it work with V2
* Fixed one behaviour in dashmate and make it use our new forked docker-compose package

## How Has This Been Tested?

Locally, and via platform-test-suite on CI (test are passing)

## Breaking Changes

No breaking changes from the users perspective. Any commands stayed the same, while internally it uses the new engine.

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2022-06-21 07:04 UTC, pshenmic commented
Original PRs are https://github.com/dashevo/platform/pull/422 (was reverted) and https://github.com/dashevo/platform/pull/433
I combined it in single PR and changed base branch to v23-dev

2022-06-21 08:48 UTC, shumkov submitted a review, later dismissed

2022-06-21 08:48 UTC, shumkov commented on packages/dashmate/src/docker/DockerCompose.js
> +      await execAsync('docker compose');
I would recommend you do both checks in one call. I mean, calling `await dockerCompose.version()` must be enough to check binaries and version?

2022-06-23 06:58 UTC, shumkov requested changes

2022-06-23 06:58 UTC, shumkov commented on packages/dashmate/src/docker/DockerCompose.js
>        if (semver.lt(version.trim(), DockerCompose.DOCKER_COMPOSE_MIN_VERSION)) {
I would recommend to move out this check form try catch block otherwise you do local catching which not good

2022-06-23 10:56 UTC, shumkov approved these changes
LGTM! 👍

2022-06-28 14:07 UTC, shumkov approved these changes
LGTM 👍

2022-06-28 14:19 UTC, merged