feat!: allow using only one index in a query
dashevo/platform pull request #77
Opened 2021-12-13 10:48 UTC by shuplenkov

## Issue being fixed or feature implemented

Since GroveDB doesn’t support indexes intersection, we need to validate query to make sure that only one index is being used.

## What was done?

allow using only one index in a query

## How Has This Been Tested?

Unit tests

## Breaking Changes

Only one index can be used in a query

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added or updated relevant unit/integration/functional/e2e tests
- [x] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [x] I have assigned this pull request to a milestone

2021-12-13 11:01 UTC, shumkov commented on packages/js-drive/lib/document/query/findNotIndexedFields.js
> +            if (indexToUse === undefined) {
Better use index names to compare

2021-12-13 12:06 UTC, shumkov commented on packages/js-drive/lib/document/query/findNotIndexedFields.js
> +              return false;
User will a consfusing error that field is not indexed.

2021-12-13 12:09 UTC, shumkov requested changes
We need to validate `orderBy` too

2021-12-14 15:11 UTC, shumkov commented on packages/js-drive/lib/document/query/validateIndexedProperties.js
> +              result.addError(new FieldsFromMultipleIndicesError(field));
Shouldn't we return from the function here?

2021-12-24 11:27 UTC, shumkov commented
@shuplenkov we got more clarity on how this thing should work:

All properties in `where` conditions must much exactly one of the indices and sequence of fields used in where must match how they defined in the index.

In `orderBy`, it can be only one property from the last condition

2022-01-07 14:00 UTC, jawid-h approved these changes
Looks legit

2022-01-07 14:01 UTC, shumkov approved these changes
👍

2022-01-07 15:57 UTC, merged