build(rs-drive-abci): update Dockerfile to Alpine and build correctly on ARM64
dashevo/platform pull request #859
Opened 2023-03-24 16:41 UTC by lklimek

## Issue being fixed or feature implemented

As learned from https://github.com/dashpay/rs-tenderdash-abci/pull/14 , cargo build takes too many resources on ARM64 target in github actions. This causes Arm64 image build to fail.

## What was done?

Added `--config net.git-fetch-with-cli=true` to address ARM build issue. See https://github.com/rust-lang/cargo/issues/10781#issuecomment-1441071052

Replace Debian base image with Apline.

## How Has This Been Tested?

On rs-tenderdash-abci, similar solution fixed the arm64 build issue: https://github.com/dashpay/rs-tenderdash-abci/actions/runs/4512281223

Locally, it also passes:

```
docker buildx build --platform linux/arm64,linux/amd64 -f packages/rs-drive-abci/Dockerfile .
```

## Breaking Changes

None

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added or updated relevant unit/integration/functional/e2e tests
- [ ] I have made corresponding changes to the documentation

**For repository code-owners and collaborators only**
- [ ] I have assigned this pull request to a milestone

2023-03-25 04:09 UTC, shumkov requested changes

2023-03-25 04:09 UTC, shumkov commented on packages/rs-drive-abci/Dockerfile
Why do you use debian instead of alpine?

2023-03-27 04:59 UTC, shumkov commented on packages/rs-drive-abci/Dockerfile
Does JS drive docker file works for you? Debian image is heavy.

2023-03-27 05:45 UTC, strophy commented on packages/rs-drive-abci/Dockerfile
Please try this approach, we can use [xx](https://github.com/tonistiigi/xx/) to compile multiarch images under Alpine without slowdowns: https://github.com/rvolosatovs/docker-protobuf/blob/main/Dockerfile#L205-L243

2023-03-29 10:16 UTC, shumkov commented on packages/rs-drive-abci/Dockerfile
>  ARG CARGO_INCREMENTAL=false
Please change ARG to ENV since it's common practice.

2023-04-01 11:12 UTC, shumkov approved these changes

2023-04-01 11:39 UTC, merged